### ISSUE TITLE
Emails da página de candidatura são enviados para todos os candidatos

### ISSUE THREAD

**Issue by edgarlpassos** [NIAEFEUP/Website-NIAEFEUP#108]
Durante a última época de recrutamento, ao enviar os emails de rejeição, fi-lo na textbox da página das candidaturas. Como a página só mostrava os users que não tinham sido aceites, pensei que só ia enviar para esses, mas enviou para todos os candidatos, inclusive os que viriam a ser aceites.

Devia ser alterado para só enviar para os que estão na página, ou só para os selecionados por checkbox.

**Comment by miguelpduarte** [comment]
Eu posso tratar disto! :smiley:
