### ISSUE TITLE
Gestão de projectos

### ISSUE THREAD

**Issue by jflcarvalho** [NIAEFEUP/Website-NIAEFEUP#113]
Colocar a gestão de projectos no nosso site de modo a o coordenador do projecto dar assignment a uma pessoa de uma coisa e aparecer na conta dela como todo, para fazer, até podemos usar parte dos trabalhos no pessoal do 3 ano de ltw, que este ano tivemos que fazer uma todo list e já temos as coisas feitas para este objectivo!

**Comment by PeaceOff** [comment]
A ideia em si é fixe. Mas acho que é para isso que serve o github
