### ISSUE TITLE
Dados no banner do NI desatualizados e hardcoded

### ISSUE THREAD

**Issue by jflcarvalho** [NIAEFEUP/Website-NIAEFEUP#114]

**Comment by PeaceOff** [comment]
Com dados , leia-se, numero de workshops, eventos, etc...

**Comment by miguelpduarte** [comment]
Já existe algo na DB para guardar essas informações? Quer seja eventos ou apenas o seu número ou assim? Só para perceber melhor o que é preciso fazer

**Comment by pedro-c** [comment]
@miguelpduarte  Acabei agora mesmo de implementar isto :) Agora é preciso uma página para criar os projectos/workshops/eventos, queres fazer?
