### ISSUE TITLE
Criar pipeline 

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/Website-NIAEFEUP#120]
Criar uma pipeline para, inicialmente, correr alguns testes de qualidade de código usando [ESLint](eslint.org) e [TravisCI](travis-ci.org). Quando estiver pronto, os pull requests devem ser protegidos pelo sucesso da pipeline.

Depende de: #118 

- [x] Correr o ESLint
- [x] Falhar se erros no ESLint
- [x] Permite merge do pull request

**Comment by PeaceOff** [comment]
Também depende de #45

**Comment by PeaceOff** [comment]
Estou a considerar este como principal. Temos de ter testes para os correr na pipeline.
