### ISSUE TITLE
Criar sistema de permissões

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/Website-NIAEFEUP#121]
Criar um sistema de permissões dinâmico em que os utilizadores ganham ou perdem acesso dependendo do seu nível de privilégios. Isto permitirá criar um sistema mais dinâmico para alteração de informações no site, permissões de outros utilizadores, etc.
Verificar se o KeystoneJS não permite algo do género. 

1. Um utilizador com a permissão `president` deve poder, além dos privilégios dos níveis abaixo:
- [ ] Mover essa permissão para outro utilizador (mudança de direção);
- [ ] Dar permissão de `board` a outros utilizadores
- [ ] Dar permissão de `member` a outros utilizadores

1. Um utilizador com a permissão `board` deve poder, além dos privilégios dos níveis abaixo:
- [ ] Mudar o banner do site

1. Um utilizador com a permissão `member` deve poder, além dos privilégios dos níveis abaixo
- [ ] Verificar candidatos ao Núcleo

1. Um utilizador com a permissão `recruit` deve poder:
- [ ] Editar o seu perfil

**Comment by bernardobelchior** [comment]
@edgarlpassos o que achas que falta?

**Comment by miguelpduarte** [comment]
Como é que funciona a permissão dos recrutas? É por omissão das outras? Os recrutas também devem poder editar o seu perfil mas não faz sentido terem acesso às candidaturas, acho.

**Comment by bernardobelchior** [comment]
Boa questão, @miguelpduarte. Vou acrescentar.

**Comment by imnotteixeira** [comment]
This issue will now be closed as per Pull Request #158

**Comment by imnotteixeira** [comment]
O PR #158 acrescentou as permissões e criou/substituiu algum do middleware existente. Contudo as funcionalidades como alterar o banner, dar permissões não foram implementadas.

Eventualmente, se virem que se justifica, criam-se issues para acrescentar essas funcionalidades.

PS: As permissões podem ser alteradas pelo Admin através da AdminUI

**Comment by miguelpduarte** [comment]
Acrescento que devido à existência da Admin UI não creio fazer sentido, pelo menos para já, ter páginas dedicadas de administração para mudar o banner e transferir permissões - estas poderão ser transferidas pelo presidente cessante na Admin UI sem qualquer problema, por exemplo, como disse o @imnotteixeira, e o banner pode ser mudado também nesta parte do site.
