### ISSUE TITLE
Criar um sistema de autodeployment

### ISSUE THREAD

**Issue by bernardobelchior** [NIAEFEUP/Website-NIAEFEUP#122]
Criar um sistema de automatic deployment em que o servidor atualiza quando um alteração é colocada no master.

**Comment by pedro-c** [comment]
@bernardobelchior  Visto seres a pessoa que melhor saber o que fazer sempre que queres dar update no servidor, não queres ajudar a fazer um script para isso?

**Comment by bernardobelchior** [comment]
Sim, tenho de pensar como fazer isto! Em último caso faço um cronjob que atualiza o site a cada hora ou coisa do género

**Comment by miguelpduarte** [comment]
Closed by https://github.com/NIAEFEUP/niployments/pull/1 and subsequent PRs

**Comment by miguelpduarte** [comment]
Closed by https://github.com/NIAEFEUP/niployments/pull/1 and subsequent PRs
