### ISSUE TITLE
Criar um botão de "Log In"

### ISSUE THREAD

**Issue by xRuiAlves** [NIAEFEUP/Website-NIAEFEUP#123]
De momento a única forma de um membro/recruta se autenticar no site é alterando o path. Acho que era mais 'agradável' em termos de utilização ter um botão para fazer log in algures.

**Comment by PeaceOff** [comment]
Certo! A ideia inicialmente era manter a existência do backoffice "escondida". Óbvio que este repo é público e por isso qql um consegue descobrir que temos um backoffice. Pode ser implementado, por mim é indiferente. O que achas @bernardobelchior  ?

**Comment by xRuiAlves** [comment]
@PeaceOff  Pois, também tinha pensado que quase de certeza que era propositado! É uma questão de preferência, era mesmo só uma sugestão.

**Comment by bernardobelchior** [comment]
É verdade! Acho que seria interessante adicionar um botão no footer. Só não digo no header porque penso que não interessará à maior parte das pessoas

**Comment by PeaceOff** [comment]
@xRuiAlves foi uma boa sugestão, obrigado!
Sugiro até que tentes fazer isso! É uma excelente oportunidade para começar.
Qualquer dúvida que tenhas estás a vontade. Podes criar um branch teu e implementar, depois fazes um pull request para o develop e identificas-me que verifico o commit.

**Comment by edgarlpassos** [comment]
@xRuiAlves Se quiseres fazer uma coisa bastante fácil podes por aqui:

![screenshot from 2018-03-31 22-50-48](https://user-images.githubusercontent.com/14338539/38167875-fd0aa6c0-3535-11e8-9e31-d258fb63847e.png)

**Comment by miguelpduarte** [comment]
Resolvido no PR #148, vou fechar :slightly_smiling_face:
