### ISSUE TITLE
Nas candidaturas é possível escolher Ano Curricular negativo

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/Website-NIAEFEUP#125]
No form de candidatura dos recrutas é possível escolher -1,-2 (testado) no campo Ano Curricular e o submit não verifica isso.

**Comment by PeaceOff** [comment]
Dei relabel porque não constitui nenhum problema de segurança. Visto que o @miguelpduarte  atribuiu o issue ao @imnotteixeira fico à espera de um pr que resolva o problema :)

**Comment by imnotteixeira** [comment]
#126
