### ISSUE TITLE
Fix fa-icons on website

### ISSUE THREAD

**Issue by imnotteixeira** [NIAEFEUP/Website-NIAEFEUP#164]
Problemas apurados:

HomePage:

- dedicação `far fa-heart`
- github `fab fa-github`
- facebook `fab fa-facebook`
- linked in `fab fa-linkedin`
- twitter `fab fa-twitter`
- insta `fab fa-instagram`

MembersPage

- github `fab fa-github`
- linkedin `fab fa-linkedin`

**Comment by miguelpduarte** [comment]
Solved in #166
