### ISSUE TITLE
Criar Sistema de Candidaturas

### ISSUE THREAD

**Issue by PeaceOff** [NIAEFEUP/Website-NIAEFEUP#42]
É interessante guardar todas a candidaturas que tivemos por época de recrutamento.
Para isso, vamos acrescentar a colecção "candidatura_arquive" e no fim de uma época de recrutamento vamos passar os dados da candidatura para o arquivo de forma a no futuro ser possível visualizar essas mesmas candidaturas.

**Comment by miguelpduarte** [comment]
É preciso ajuda neste issue? @jflcarvalho

**Comment by imnotteixeira** [comment]
Vou pegar nesta issue e acrescentar um pouco (maybe not) de complexidade. Neste sistema de candidaturas é suposto:

- Separar candidaturas/épocas de recrutamento por ano/fase de recrutamento
- Definir facilmente o ínicio e o fim de uma determinada fase de recrutamento (possibilidade de criação das mesmas por parte do Presidente)
- Não usar o .env para determinar épocas de recrutamento

Para isto, são necessários 3 modelos:
- FaseCandidatura: caraterizada pelo ano e pela fase em si (um inteiro auto-increment); e pela data de inicio e de fim. Não se podem sobrepor duas fases.
- Candidato: caraterizado pelo nome, idade, ano, curso, etc (info contida no formulário)
- Candidatura: dois campos do tipo Pair <Pergunta:string, Resposta:string>, permitindo que se possa variar as perguntas feitas em diferentes fases e um campo "more:string" em que o candidato escreve algo a acrescentar

O UML está disponível na imagem abaixo:


![UML](https://user-images.githubusercontent.com/28157246/45120519-46ec5f80-b156-11e8-9d8a-fb20bda5a698.jpg)
