### ISSUE TITLE
Can't delete candidate

### ISSUE THREAD

**Issue by edgarlpassos** [NIAEFEUP/Website-NIAEFEUP#63]
For any candidate, accepted or not, before or after an interview, there is no way to delete the submission. This may lead to unwanted clutter in the interviews page.

![screenshot from 2017-10-10 19-12-49](https://user-images.githubusercontent.com/14338539/31402959-969c4998-adef-11e7-8d41-551e1db700ea.png)

^No option to delete the submissions

**Comment by PeaceOff** [comment]
Como admin podes eliminar na Admin UI, só não se fez isso porque queriamos guardar essas informações.
O que se pode fazer é não mostrar um candidato que ja foi aceite por exemplo
